### ISSUE TITLE
EXCEPTION! Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by JCAELA** [OpenDroneMap/Obj2Tiles#11]
While running the full pipeline of Obj2Tiles I get the "Specified argument was out of the range of valid values" exception.
Does anyone know what causes it and how to solve it?

Thank you
![error_obj2tiles](https://user-images.githubusercontent.com/100201026/177045893-09a10d4d-a8c2-4514-90d9-28fbbcf25101.PNG)

**Comment by HeDo88TH** [comment]
Can you provide your input data and parameters? Thanks

**Comment by JCAELA** [comment]
[https://res-2.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]chimney (2).zip<https://1drv.ms/u/s!As4q1gtrMLc6kCioSzwMzte8x9Rm>

Hi Luca,

Thanks for your prompt response.
Above is the link with the obj model.

I used the default scripts and parameters:
Obj2Tiles chimney.obj ./output
Obj2Tiles --lods 3 --divisions 3 --lat 40.689434025350025 --lon -74.0444987716782 --alt 120 chimney.obj ./output

The two seem to successfuly complete the splitting stage but fail the next steps.

Cordially

José

________________________________
De: Luca Di Leo ***@***.***>
Enviado: terça-feira, 5 de julho de 2022 08:57
Para: OpenDroneMap/Obj2Tiles ***@***.***>
Cc: JCAELA ***@***.***>; Author ***@***.***>
Assunto: Re: [OpenDroneMap/Obj2Tiles] EXCEPTION! Specified argument was out of the range of valid values (Issue #11)


Can you provide your input data and parameters? Thanks

**Comment by HeDo88TH** [comment]
Does it work with the new version?

**Comment by JCAELA** [comment]
Hi Luca,

It does! Thank you very much.
I wanted to test with more models before I confirm. I will test with larger files and see if it works as well.

Kindest regards

José

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HeDo88TH** [comment]
> Hi Luca, It does! Thank you very much. I wanted to test with more models before I confirm. I will test with larger files and see if it works as well. Kindest regards

Thanks!
