### ISSUE TITLE
 Exception: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by zhangdachen** [OpenDroneMap/Obj2Tiles#14]
Exception: Index was outside the bounds of the array.

**Comment by zhangdachen** [comment]
![image](https://user-images.githubusercontent.com/12945124/181459929-f767db07-8306-42dd-a213-17ee3186ec81.png)

**Comment by HeDo88TH** [comment]
Hello, can you provide the input data?

**Comment by zhangdachen** [comment]
I put the data  [here](https://github.com/zhangdachen/Models)
The command I execute is
`Obj2Tiles ..\Models\new_scene_0.obj ./output`

**Comment by zhangdachen** [comment]
hello,
how is it，

**Comment by HeDo88TH** [comment]
This is a bug, I can repro it but no solution is available yet

**Comment by uglyer** [comment]
I also encountered this problem, the reason is that the `clusterBoundary` is less than a range of less than 0 when pack the texture, I will fix this problem later.

**Comment by zhangdachen** [comment]
> I also encountered this problem, the reason is that the `clusterBoundary` is less than a range of less than 0 when pack the texture, I will fix this problem later.

能给打个包吗，我试试能不能行，电脑上没有core环境。

**Comment by HeDo88TH** [comment]
Unfortunately #16 does not address the problem. The obj model is invalid since it has several texture coordinates > 1:

```
vt 2.0000 0.0000
vt 2.0000 0.4830
```

This is out of spec https://en.wikipedia.org/wiki/Wavefront_.obj_file#File_format .

**Comment by HeDo88TH** [comment]
I will close this until new data comes up.

**Comment by HeDo88TH** [comment]
Confirmed, waiting for fix 👍

**Comment by Rakiah** [comment]
I'm having same issue

**Comment by Rakiah** [comment]
using -k (keepTextures) works for me, i suppose the problems lies on the texture packing process

**Comment by uglyer** [comment]
I misunderstood at first, uv is not limited to the range of 0~1, when the value is 1.5, it is consistent with 0.5
