### ISSUE TITLE
a BUG

### ISSUE THREAD

**Issue by GRBicycle** [OpenDroneMap/Obj2Tiles#15]
Box3 Bounds in  Mesh.cs，
                  maxX = v.X > maxX ? maxX : v.X;
                  maxY = v.Y > maxY ? maxY : v.Y;
                  maxZ = v.Z > maxZ ? maxZ : v.Z;
pls revise it

**Comment by HeDo88TH** [comment]
What is wrong about that?

**Comment by GRBicycle** [comment]
why not  maxX = v.X > maxX ?  v.X:maxX

**Comment by HeDo88TH** [comment]
Because it would be pointless. The aim, if I recall correctly, is to limit the coordinates to those max values. So, if X > MAX use MAX otherwise XIl 1 Ago 2022 07:23, GRBicycle ***@***.***> ha scritto:
why not  maxX = v.X > maxX ?  v.X:maxX

**Comment by GRBicycle** [comment]
Let me check again. Thanks for your reply

**Comment by HeDo88TH** [comment]
I will re-open this issue if anything new comes out
