### ISSUE TITLE
Question about the generated number of b3dm files

### ISSUE THREAD

**Issue by cbtogu** [OpenDroneMap/Obj2Tiles#18]
Hi, Thanks for your great work and make it open source.  I have some questions about the LODs when I found that it contains the same number of b3dm files under every LOD folder. 
If I understand it correctly, the number of b3dm files at each level` i `should be:
`N = 4^(lods -i -1) ` if the mesh is splitted in a quadric way.
So it should contain the most b3dm files at LOD 0 ( the finest level) , the least at the top level, which is the coarsest level.
So I think the number of splitted mesh generated by Obj2Tiles is not right.
Please correct me if I'm wrong. Thank you.

**Comment by HeDo88TH** [comment]
No, the LODs are obtained by lowering the poly count in the first processing step.
All LODs have the same number of "tiles", they are more or less detailed.

**Comment by cbtogu** [comment]
>

**Comment by cbtogu** [comment]
> No, the LODs are obtained by lowering the poly count in the first processing step. All LODs have the same number of "tiles"

Do you process the LODs in this way deliberately ? Because according to  the [3dtiles specification](https://github.com/CesiumGS/3d-tiles/tree/main/specification) ,  the number of the child nodes should be greater than that of the father's. Please check.
![image](https://user-images.githubusercontent.com/8542078/185018984-5ab2ec8c-77d1-4e96-a2c6-6fe84776b4df.png)

**Comment by cbtogu** [comment]
Sorry for closing the issue by mistake, re-open it.

**Comment by HeDo88TH** [comment]
Actually we use the replacement method to have multiple LODs and every LOD has the same tree
