### ISSUE TITLE
Getting error "Exception: Input string was not in a correct format."

### ISSUE THREAD

**Issue by murphysurveys** [OpenDroneMap/Obj2Tiles#19]
On processing an OBJ with default or specified settings, I get the error:

Exception: Input string was not in a correct format.

(using v1.0.9 and v1.0.8 on Windows x64)

**Comment by HeDo88TH** [comment]
Can you provide the input data?

**Comment by HeDo88TH** [comment]
Can you provide the input data?

**Comment by HeDo88TH** [comment]
I'm closing this until the input data is provided
