### ISSUE TITLE
after converted, missing color message

### ISSUE THREAD

**Issue by zuixiaosanlang** [OpenDroneMap/Obj2Tiles#24]
command
Obj2Tiles.exe --lods 8 --divisions 3 --keeptextures --lat 40.689434025350025 --lon -74.0444987716782 --alt 120  mesh/mesh.obj ./output

view:
![image](https://user-images.githubusercontent.com/20105627/196383482-d863d66e-9269-4207-8fe0-a715e04a4ce4.png)

but my obj is
![image](https://user-images.githubusercontent.com/20105627/196383758-eb71609e-a7e9-4129-8e34-cf255f8263df.png)

anything i missing ??

thanks

**Comment by IKangXu** [comment]
How to solve ?
