### ISSUE TITLE
All the LODs have the same blocks

### ISSUE THREAD

**Issue by zuixiaosanlang** [OpenDroneMap/Obj2Tiles#25]
i find all the LODs have the same blocks。

**Comment by pierotofy** [comment]
It does have HLOD capabilities. Perhaps something is unique about your input that's causing the program to not be able to decimate it.

**Comment by zuixiaosanlang** [comment]
@pierotofy thank you for reply.
i mean different HOD, have different divisions. for example, divisions of LOD-0 is 3, and  LOD-1 is 2,  LOD-2 is 1. 
now i found all the divisions of LOD-3,2,1  are 3.
![image](https://user-images.githubusercontent.com/20105627/197430158-01c17adc-17e7-44e0-a37a-a6d4f2573cec.png)

**Comment by HeDo88TH** [comment]
Yes, this is by design: every LOD has the same number of divisions.
Can you provide your test data?

**Comment by zuixiaosanlang** [comment]
@HeDo88TH
i am sorry. i donot express clearly before.

about the converted result, i found all the folders(LOD-0,1,2) are very close in size.

for example,in my test,
LOD-0 is 27.3M, and LOD-1 is 24.2M, and LOD-2 is 20.7M

But i want to get the result like this:
LOD-0 is 28M, and LOD-1 is 14M, and LOD-2 is 7M

Top level has smaller size obviously。

i donot know to change the code. 

i noticed in the decimate stage, the size of objs are different obviously.(mesh.obj is 62M, mesh_0.obj is 42M, mesh_1.obj is 25M).

any suggest ??

thanks

**Comment by HeDo88TH** [comment]
The size is mostly correlated to the textures. The OBJ is basically a text file with a bunch of vertices and faces. We could reduce the quality of the textures or their size in the LOD process but it's currently not implemented.
