### ISSUE TITLE
Getting element not supported error when trying to generate 3d tiles.

### ISSUE THREAD

**Issue by lavisht22** [OpenDroneMap/Obj2Tiles#30]
I am trying to generate 3d tiles from an obj dataset and I keep running into this error:
 
![image](https://user-images.githubusercontent.com/22209892/200786064-112da567-87c8-4281-b81f-39d9d9724408.png)

No files are generated in output directory. Is there a better way to debug this or anyone possibly have any explanation on why is this failing?

**Comment by pierotofy** [comment]
Can you share the input model you used?

**Comment by jingyangking** [comment]
> I am trying to generate 3d tiles from an obj dataset and I keep running into this error:
> 
> ![image](https://user-images.githubusercontent.com/22209892/200786064-112da567-87c8-4281-b81f-39d9d9724408.png)
> 
> No files are generated in output directory. Is there a better way to debug this or anyone possibly have any explanation on why is this failing?

I also sent this problem. Have you solved it? What is the reason for it？
